SGLC/urls.py
#encoding:utf-8
from django.conf.urls import patterns, include, url

from apps.account.urls import account_urls
from apps.process_admin.urls import process_admin_urls
from apps.actions_log.urls import actions_log_urls
from apps.production_orders.urls import production_orders_urls
from apps.payroll.urls import payroll_urls
from apps.pdfmodule.urls import pdfmodule_urls
from apps.inventory.urls import inventory_urls
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'apps.website.views.home', name='home'),
    url(r'^conozca-destaju$', 'apps.website.views.description', name='description'),
    url(r'^cuenta/', include(account_urls)),
    url(r'^administracion/', include(process_admin_urls)),
    url(r'^historial/', include(actions_log_urls)),
    url(r'^ordenes-de-produccion/', include(production_orders_urls)),
    url(r'^nomina/', include(payroll_urls)),
    url(r'^pdf/', include(pdfmodule_urls)),
    url(r'^almacen/', include(inventory_urls)),
    url(r'^ajax/editinline$', 'apps.website.views.ajax_edit_in_line', name="edit_in_line"),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

# try:
#     from django.conf.urls.defaults import handler500
# except:
#     from django.conf.urls import handler500
# handler500 = "apps.website.views.server_error"

apps/production_orders/urls.py
from django.conf.urls import patterns, url


generation_of_production_order = patterns('apps.production_orders.views',
    url(r'^ordenes-de-produccion/$', 'create_production_order', name="create_production_order"),
    url(r'^editar-orden-de-produccion/(?P<id_production_order>[0-9]+)', 'update_production_order', name="update_production_order"),
    url(r'^eliminar-orden-de-produccion/(?P<id_production_order>[0-9]+)', 'delete_production_order', name="delete_production_order"),
    url(r'^generar-pdf/(?P<id_production_order>[0-9]+)', 'generate_pdf', name="generate_pdf")
)

filling = patterns('apps.production_orders.views',
    url(r'^llenado_de_op/$', 'filling_pro_ord', name="filling_pro_ord"),
    url(r'^llenar/(?P<id_production_order>[0-9]+)$', 'filling', name="filling"),
)
 
qualification = patterns('apps.production_orders.views',
    url(r'^calificacion_de_op/$', 'qualification_pro_ord', name="qualification_pro_ord"),
    url(r'^calificar/(?P<id_production_order>[0-9]+)$', 'qualification', name="qualification"),
)

approval = patterns('apps.production_orders.views',
    url(r'^aprobacion_de_op/$', 'approval_pro_ord', name="approval_pro_ord"),
    url(r'^aprobar/(?P<id_production_order>[0-9]+)$', 'approval', name="approval"),
)

list_pro_ord = patterns('apps.production_orders.views',
    url(r'^consultar_op/$', 'list_production_orders', name="list_production_orders"),
    url(r'^ver_op/(?P<id_production_order>[0-9]+)$', 'show_production_order_ajax', name="show_production_order_ajax"),
)



production_orders_urls = generation_of_production_order + filling + qualification + list_pro_ord + approval

apps/inventory/models.py
# encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from apps.process_admin.models import Tools
from apps.production_orders.models import ProductionOrder

class GenericManager(models.Manager):

    def get_all_active(self):
        return self.filter(is_active=True).order_by('-date_modified')

    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except self.model.DoesNotExist:
            return None



class Inventory(models.Model):

    tool = models.ForeignKey(Tools, related_name='%(class)s_tool') 
    quantity = models.FloatField(max_length=20, verbose_name="Quantity", null=False)

    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    objects = GenericManager()
    
    def __unicode__(self):
        return "%s: %s"%(self.tool, self.quantity)

    def get_unit_value(self):
        quantitiprovidertool_list = QuantityProviderTool.objects.filter(tool=self.tool, is_active=True, provider_order__status_order="Approved")
        c1 = 0
        c2 = 0
        for quantitiprovidertool_obj in quantitiprovidertool_list:
            c1 = c1+quantitiprovidertool_obj.quantity
            c2 = c2 + quantitiprovidertool_obj.quantity*quantitiprovidertool_obj.unit_value
        if c1 == 0:
            return 0
        else:
            return c2/c1

    def get_total_value(self):
        return self.get_unit_value()*self.quantity 

    
class ProviderOrder(models.Model):

    STATUS_CHOICES =( ('Waiting','En espera'), ('Approved','Aprobada'), ('Not_Approved','No aprobada'))

    user_generator = models.ForeignKey(User, related_name='%(class)s_user_generator') 
    user_provider = models.ForeignKey(User, related_name='%(class)s_user_provider') 
    user_approver = models.ForeignKey(User,  null=True, blank=True, related_name='%(class)s_user_approved') 
    invoice_number = models.CharField(max_length=50, verbose_name="Invoice number", blank=True, null=True, default='---')
    details = models.TextField(blank=True, null=True)
    status_order = models.CharField(max_length=20, choices=STATUS_CHOICES,  default='Waiting')
    date_approved = models.DateTimeField(null=True, blank=True)

    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    objects = GenericManager()
    
    def __unicode__(self):
        return "%s - [%s] - %s"%(self.id, self.invoice_number, self.user_generator.get_full_name())


class EmployedOrder(models.Model):

    TYPE_CHOICES =( 
        ('Recovery','Retorno al almacen'),    
        ('Output','Salida por OP'), 
        ('Output_Stock','Salida por almacen')
    )

    STATUS_CHOICES =( 
        ('Waiting','En espera'), 
        ('Approved','Aprobada'), 
        ('Not_Approved','Rechazada'),
        ('Not_Approved_OP',u'Rechazada automaticamente por Modificación de OP'),
        ('Not_Approved_OP_Canceled',u'Rechazada automaticamente por Cancelación de OP')
    )

    user_approver = models.ForeignKey(User,  null=True, blank=True, related_name='%(class)s_user_approver') 
    user_generator = models.ForeignKey(User, related_name='%(class)s_user_generator') 
    production_order = models.ForeignKey(ProductionOrder, related_name='%(class)s_production_order') 
    type_order = models.CharField(max_length=50, choices=TYPE_CHOICES)
    details = models.TextField(blank=True, null=True)
    status_order = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Waiting')
    date_approved = models.DateTimeField(null=True, blank=True)

    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    objects = GenericManager()
    
    def __unicode__(self):
        return "%s - %s"%(self.id, self.user_generator.get_full_name())
    

class QuantityProviderTool(models.Model):

    tool = models.ForeignKey(Tools, related_name='%(class)s_tool') 
    quantity = models.FloatField(max_length=20, verbose_name="Quantity", null=False)
    unit_value = models.FloatField(max_length=30, verbose_name="Unit value", null=False)
    provider_order = models.ForeignKey(ProviderOrder, null=True, blank=True, related_name='%(class)s_provider_order') 

    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    objects = GenericManager()
    
    def __unicode__(self):
        return "%s - %s: %s"%(self.id, self.tool, self.quantity)

    

class QuantityEmployedTool(models.Model):

    tool = models.ForeignKey(Tools, related_name='%(class)s_tool') 
    quantity = models.FloatField(max_length=20, verbose_name="Quantity", null=False)
    employed_order = models.ForeignKey(EmployedOrder, related_name='%(class)s_employed_order') 

    is_active = models.BooleanField(default=True)
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    objects = GenericManager()
    
    def __unicode__(self):
        return "%s: %s"%(self.tool, self.quantity)
    

apps/production_orders/models.py
# encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from apps.process_admin.models import Tools, Activities, Places
from apps.payroll.models import Payroll

class GenericManager(models.Manager):

    def get_all_active(self):
        return self.filter(is_active=True).order_by('-date_modified')

    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except self.model.DoesNotExist:
            return None


class ProductionOrder(models.Model):
    """Table for generate the production order"""
    user = models.ForeignKey(User,  null=False, related_name='%(class)s_user') 
    activity = models.ForeignKey(Activities,  null=False, related_name='%(class)s_activity')
    place = models.ForeignKey(Places,  null=False, related_name='%(class)s_place')
    status = models.IntegerField(default=1, 
            choices=(
                (1,"Generada"),
                (2,"Llena"),
                (3,"Ya calificada - no verificada"),
                (4,"En nomina"),
                (5,"No calificada - ya verificada"),
                (6,"Ya calificada - ya verificada")
            )
        )
    is_active = models.BooleanField(default=True)
    responsible = models.ManyToManyField(User)
    modifications = models.IntegerField(default=0)
    comments = models.TextField(blank=True)
    
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    objects = GenericManager()
    
    payroll = models.ForeignKey(Payroll,  null=True, related_name='%(class)s_payroll')
    
    def __unicode__(self):
        return "%s - %s "%(self.id, self.activity.name)
    
    def get_table_name(self):
        return u"Orden de producción"

    def get_employed_orders_output_approved(self):
        return self.employedorder_production_order.get_all_active().order_by('-date_added')

    def get_employed_orders_for_op(self):
        return self.employedorder_production_order.get_all_active().filter(status_order="Waiting",type_order="Output").order_by('-date_added')


class FillingProOrd(models.Model):
    user = models.ForeignKey(User,  null=False, related_name='%(class)s_user')
    production_order = models.OneToOneField(ProductionOrder)
    comments = models.TextField(blank=True)
    
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return "%s : %s"%(self.user, self.production_order)

    
class QualificationProOrd(models.Model):
    user = models.ForeignKey(User,  null=True, blank=True, related_name='%(class)s_user') 
    production_order = models.OneToOneField(ProductionOrder)
    comments = models.TextField(blank=True)
    value = models.IntegerField(default=4,  choices=((1,"Malo"),(2,"Regular"),(3,"Bueno"), (4,"Muy bueno"), (5,"Excelente")))
    is_qualified = models.BooleanField(default=False)

    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return "%s : %s"%(self.user, self.production_order)


class ApprovalProOrd(models.Model):
    user = models.ForeignKey(User,  null=True, blank=True, related_name='%(class)s_user') 
    production_order = models.OneToOneField(ProductionOrder)
    comments = models.TextField(blank=True)
    status = models.IntegerField(default=2,  choices=((1,"Aprobada"),(2,"Rechazada")))
    is_verified = models.BooleanField(default=False)

    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return "%s : %s"%(self.user, self.production_order)


class Filling(models.Model):
    user = models.ForeignKey(User,  null=False, related_name='%(class)s_user') 
    value = models.FloatField(max_length=100, verbose_name="value", null=False)
    time = models.FloatField(max_length=20, verbose_name="Time", null=True, blank=True)
    filling_pro_ord = models.ForeignKey(FillingProOrd,  null=False, related_name='%(class)s_filling_pro_ord')
    comments = models.TextField(blank=True)
    
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s - %s : %s"%(self.user, self.filling_pro_ord, self.value)
    
    def activity_value(self):
#        print "obj",self.value
#        print "Activity", self.filling_pro_ord.production_order.activity.value
#        print "Total", int(self.value) * int(self.filling_pro_ord.production_order.activity.value)
        return int(round(self.value * self.filling_pro_ord.production_order.activity.value,0))

apps/production_orders/forms.py
#encoding:utf-8
from django import forms
from apps.production_orders.models import ProductionOrder, FillingProOrd, QualificationProOrd, Filling, ApprovalProOrd
from apps.process_admin.models import Activities, Places, Tools, UserProfile
from django.contrib.auth.models import User


def user_unicode(self):
    try:
        dni = self.userprofile.dni
    except:
        dni = "Sin DNI"
    return  self.username if self.get_full_name() == ""  else u"%s - %s" % (dni, self.get_full_name())

User.__unicode__ = user_unicode


class ProductionOrderForm(forms.ModelForm):
    queryset_activity = Activities.objects.filter(is_active=True,is_available=True)
    queryset_place = Places.objects.filter(is_active=True, is_available=True)
    queryset_responsable = User.objects.filter(userprofile__is_active_worker=True, userprofile__user_type__pk = 7)
    # queryset_tools = Tools.objects.filter(is_active=True, is_available=True) 
    
    activity = forms.ModelChoiceField(label="Actividad", queryset=queryset_activity)
    place = forms.ModelChoiceField(label="Lugar", queryset=queryset_place)
    responsible = forms.ModelMultipleChoiceField(label="Responsables", queryset=queryset_responsable,  widget= forms.SelectMultiple(attrs={'class': 'chosen-select', 'data-placeholder':"Selecciona los responsables"}))
    # tools = forms.ModelMultipleChoiceField(label="Herramientas", queryset=queryset_tools, required=False, widget= forms.SelectMultiple(attrs={'class': 'chosen-select', 'data-placeholder':"Selecciona las herramientas"}))
    comments = forms.CharField(label=u"Observaciónes", widget=forms.TextInput(attrs={'placeholder': u"Observaciónes"}), required=False)

    class Meta:
        model = ProductionOrder
        fields = ('activity', 'place', 'responsible', 'comments')


class FillingForm(forms.ModelForm):
    value = forms.CharField(label="Tiempo", widget=forms.TextInput(attrs={'placeholder': 'cantidad','type':"number","step":"any"}))
    # time = forms.CharField(label="Tiempo (H)", widget=forms.TextInput(attrs={'placeholder': 'tiempo en horas','type':"number","step":"any"}))
    comments = forms.CharField(label=u"Observaciónes", widget=forms.TextInput(attrs={'placeholder': u"Observaciónes"}), required=False)

    class Meta:
        model = Filling
        fields = ('user', 'value', 'comments')
        widgets = {
            'user': forms.Select(attrs={'class':'name-only'}),
        }


class FillingProOrdForm(forms.ModelForm):
    comments = forms.CharField(label=u"Observaciónes Generales", widget=forms.TextInput(attrs={'placeholder': u"Observaciónes Generales"}), required=False)
    class Meta:
        model = Filling
        fields = ('comments',)
#        widgets = {
#            'user': forms.Select(attrs={'class':'name-only'}),
#        }



class QualificationsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(QualificationsForm, self).__init__(*args, **kwargs)
        self.fields['value'].label = "Valor"
        
    comments = forms.CharField(label=u"Observaciónes", widget=forms.TextInput(attrs={'placeholder': u"Observaciónes"}), required=False)

    class Meta:
        model = QualificationProOrd
        fields = ('value', 'comments')



class ApprovalForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ApprovalForm, self).__init__(*args, **kwargs)
        self.fields['status'].label = "Estado"
        
    comments = forms.CharField(label=u"Observaciónes", widget=forms.TextInput(attrs={'placeholder': u"Observaciónes"}), required=False)

    class Meta:
        model = ApprovalProOrd
        fields = ('status', 'comments')
        

class ListProductionOrderForm(forms.Form):
    TYPE_CHOICES=[
                  ('added',u"Creación"),
                  ('modified',u"Modificación"),
                  ('filling',u"LLenado")
                  ]
    
    date_from = forms.DateTimeField(label="Desde", widget=forms.widgets.DateTimeInput(attrs={'class': 'date-pick'}), input_formats=['%Y-%m-%d'])
    date_to = forms.DateTimeField(label="Hasta", widget=forms.widgets.DateTimeInput(attrs={'class': 'date-pick'}), input_formats=['%Y-%m-%d'])
    type_date = forms.ChoiceField(label="Fecha",choices=TYPE_CHOICES)

apps/production_orders/templates/approval_form.html
{% extends "approval_pro_ord.html" %}

{% block modal%}
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> <!-- Ventana Modal para agregar actividades. -->
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4>
                APROBAR ORDEN DE PRODUCCI&Oacute;N
                </h4>
                Actividad: {{ po.activity.name }}
            </div>
            <form method = "POST"  enctype="multipart/form-data" id="Form">
            {% csrf_token %}
            
            <div class="modal-body">
                <div class="panel panel-warning panel-daiech">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            Formulario para aprobar ordenes de producci&oacute;n para n&oacute;mina
                        </h3>
                    </div>
                    <table class="table table-hover table-condensed table-striped">
                    {{ form }}
                    </table>
                    
                    {% include "resume_production_order_json.html" %}
                </div>
            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="_create">Guardar</button>
                <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Cerrar</button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/production_orders/templates/approval_pro_ord.html
{% extends "base.html" %}
{% block TITLE %}Llenado de ordenes de producci&oacute;n {% endblock %}
{% block content %}

<div class="panel panel-warning panel-daiech">
    <div class="panel-heading">
        <h3 class="panel-title ">Verificar ordenes de produccion para n&oacute;mina</h3>
    </div>
    <div class="table-responsive">
    <table id="dataTable" class="table table-hover table-condensed table-striped">
        <thead>
        <tr>
            <th></th>
            <th>Estado</th>
            <th>#</th>
            <th>Creador</th>
            <th>Actividad</th>
            <th>Lugar</th>
            <th>Herramientas</th>
            <th>Responsables</th>
            <th>Fecha llenado</th>
            <th>Fecha de verificaci&oacute;n</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in object_list %}
        <tr>
            <td class="actions">
            	{% if obj.approvalproord.is_verified %}
                    {% if obj.approvalproord.status = 1 %}
            	       <span title="Ya se aprob&oacute;" class="glyphicon glyphicon-ok" ></span>
                    {% else %}
                        <span title="No se ha aprobado" class="glyphicon glyphicon-remove" ></span>                
                    {% endif %}
                {% else %}
                    <span title="No se ha verificado" class="glyphicon glyphicon-time" ></span>
                {% endif %}
            </td>
            <td>
            
            {% if obj.approvalproord.is_verified %}
                    {{ obj.approvalproord.get_status_display }}
            {% else %}
                -------
            {% endif %}
            </td>
            <td >{{obj.pk}}</td>
            <td>{{obj.user.username}}</td>
            <td>{{obj.activity.name}}</td>
            <td>{{obj.place.name}}</td>
            <td>
                <ul>
                {% for tool in obj.tools.all %}
                    <li>{{ tool }}</li>
                {% endfor %}
                </ul>
            </td>
            <td>
                <ul>
                {% for user in obj.responsible.all %}
                    <li>{{ user.get_full_name }}</li>
                {% endfor %}
                </ul>
            </td>
            <td><span title="{{obj.last_filling}}">{{obj.last_filling|date:"Y/m/d G:i"}}</span></td></td>
            <td><span title="{{obj.approvalproord.date_verified}}">{{obj.approvalproord.date_verified|date:"Y/m/d G:i"}}</span></td>
            <td class="actions">
                {% if not obj.approvalproord.is_verified  %}
                <a href="{% url 'approval' obj.id %}" title="Calificar esta orden de producci&oacute;n" class="btn"><span class="glyphicon glyphicon-ok-circle" ></span></a>
                {% elif obj.approvalproord.is_verified %}
                <a href="{% url 'approval' obj.id %}" title="Editar esta calificacion orden de producci&oacute;n" class="btn"><span class="glyphicon glyphicon-pencil" ></span></a>
                {% else %}
                ERROR
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>
</div>

{% block modal %}
{% endblock %}

{% endblock %}

{% block style %}
<style type="text/css">
    .actions .btn{padding: 0;}
    .panel-title{line-height: 34px;}
</style>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function(){
        {% if show_form %}
                $('#formModal').modal('show')
        {% endif %}
        $("span").tooltip();
        {% if form_mode ==  "_update" %}
            $('#formModal').on('hidden.bs.modal', function () {
                top.location = "{% url 'approval_pro_ord' %}"
            });
        {% endif %}
        /* dataTables jQuery plugin activation setDataTables(id_table)*/
        setDataTables('#dataTable')
        
        $(".name-only").each(function(i){
            var t = $(this).find("option:selected").text();$(this).css("display", "none");
            $(this).parent().append(t)})
    });
</script>
{% endblock %}

apps/production_orders/templates/generate_pdf.html
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
        body{font-family:Helvetica;color: #555;}
        #footerContent{
            margin: 20px 0;
            margin-top: 45px;
        }
        .box{overflow: hidden;}
        .box > div{float: left;width: 50%}
        #headerContent{margin: 0}
        h1, h2 {text-align: center}
        th{text-align: left;vertical-align: center;}
        th, td{padding: 3px}
        #headerContent > div > img{height:50px;width:100px;margin:0;margin-top:0;}
        .div-header{height:50px;max-width:100px;display:inline-block;margin:0;}
        #payrollContent{line-height: 1.8;margin: 0}
        table{width: 100%}
        @page {
          margin: 2.5cm;
          margin-top: 3cm;
          margin-bottom: 2.5cm;
          font-size: 28px;
          colordisplay:#555;
          @frame header {
            -pdf-frame-content: headerContent;
            top: 1cm;
            margin-left: 2.1cm;
            margin-right: 1cm;
            height: 2.5cm;
          }
          @frame footer {
            -pdf-frame-content: footerContent;
            bottom: 1cm;
            margin-left: 2.5cm;
            margin-right: 1cm;
            margin-top: 1.5cm;
            height: 2cm;
          }
        }
    </style>
</head>
<body>
<h1>Orden de produccion #{{obj.pk}}</h1>
<h2>{{obj.date_added}}</h2>
<br />
<table border="1">
    <tr><td>Creador</td><td>{{obj.user.get_full_name}}</td></tr>
    <tr><td>Actividad</td><td>{{obj.activity.name}}</td></tr>
    <tr><td>Lugar</td><td>{{obj.place.name}}</td></tr>
    <tr><td>Responsables</td><td><ul>{% for r in obj.responsible.all %}<li>{{r.get_full_name}}</li>{% endfor %}</ul></td></tr>
    <tr><td>Observaciones</td><td>{{obj.comments}}</td></tr>
</table>

  <h3>
    Ordenes de items de inventario
  </h3>

<table border="1">
  {% for employed_order in obj.get_employed_orders_for_op %}
  <tr><td colspan="2"><strong>No. Orden de inventario de empleado: {{ employed_order.id}} / {{ employed_order.get_status_order_display }} / {{ employed_order.get_type_order_display }} </strong></td></tr>
    {% for item in employed_order.quantityemployedtool_employed_order.all %}
      <tr><td class="text-right">{{ item.tool.name }}</td><td class="text-right" >{{ item.quantity }}</td></tr>
    {% endfor %}
  {% endfor %}
</table>
</body>
</html>

apps/production_orders/templates/show_production_order.html
{
	"pk": "{{pro_ord_obj.pk}}",
	"status": {% if pro_ord_obj.status == 1 %}
					"Generada",
				{% elif pro_ord_obj.status == 2 %}
					"llena",
				{% elif pro_ord_obj.status == 3 %}
					{% if pro_ord_obj.qualificationproord.status == 1%}
                	"Calificada y Aprobada",
                	{%else%}
                	"Calificada y No Aprobada",
                	{%endif%}
				{% elif pro_ord_obj.status == 4 %}
					"En nomina",
				{% else %}
					"ERROR",
				{% endif %}
	"activity": "{{pro_ord_obj.activity.name}}",
	"place": "{{pro_ord_obj.place.name}}",
	"date_added":"{{pro_ord_obj.date_added}}",
	"date_modified":"{{pro_ord_obj.date_modified}}",
	"comments":{
		"generated": "{{ pro_ord_obj.comments }}",
		"filling": "{{ pro_ord_obj.fillingproord.comments}}",
		"qualified": "{{ pro_ord_obj.qualificationproord.comments}}"
	},
	"responsible": [
		{% for e in filling_list %}
			{"name": "{{e.user.get_full_name}}","filling":"{{e.value}}"},
		{% endfor %}
		{"": ""}
	]
}           